### ISSUE TITLE
Use `dnote-io` for managing [topic]_notes.txt files

### ISSUE THREAD

**Issue by marfvr** [robertodessi/custom_config#1]
FEATURE REQUEST

Why don't use [dnote](https://github.com/dnote-io/cli) for taking notes? It seems quite easy to use and more usable than editing one file per topic.

For example, to add a note to one topic:

    dnote add [book name] -c "[content]"

Where [book name] can be `git`, `vim` or something else, while `content` is the content of the note.

**Comment by robertodessi** [comment]
It seems pretty nice. I've used a simple cli tool to set reminders [(http://todolist.site/)](url) but found it a bit too annoying and ended not checking it as often as needed. Good ol' terminal for notes and reminders has been working fine for me so far so I believe I'll stick with it.
Thanks for the suggestion though!
